global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#andrey-kuznetsov'
